apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.clusterName }}-md-0
  namespace: {{ .Values.clusterNamespace | default "default" }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: gce
          name: {{`'{{ ds.meta_data.local_hostname.split(".")[0] }}'`}}