apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  selector:
      matchLabels:
        app: cluster-autoscaler
  template:
    spec:
      containers:
        - name: cluster-autoscaler
          args:
          - --kubeconfig=/mnt/capi-dev.kubeconfig
          - --clusterapi-cloud-config-authoritative
          - --cloud-provider=clusterapi
          - --node-group-auto-discovery=clusterapi:clusterName=capi-dev
      volumes:
      - name: kubeconfig-vol
        secret:
          secretName: capi-dev-kubeconfig
